// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2021 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20210406
'use strict';(function(){var e,Ta,I,N,E=!1,ta;const u=window,F=document,ua=function(){},k=Function.prototype.call,J=Object,ha=URL,U=Date,yb=Blob,zb=u.fetch.bind(u),Ab=XMLHttpRequest,{runtime:{setUninstallURL:Bb,onMessage:Cb,onStartup:Db,onInstalled:Eb},tabs:{executeScript:Ua,create:ia,remove:Va,update:va,query:O,move:Fb,onCreated:Wa,onUpdated:K,onRemoved:Xa},windows:{getAll:Ya,create:ja,update:Za,getLastFocused:Gb,onRemoved:wa},browserAction:{setTitle:Hb,setBadgeBackgroundColor:Ib,setBadgeText:Jb},
browsingData:{remove:V},history:{deleteUrl:W,search:xa,getVisits:Kb,deleteRange:Lb,onVisited:$a,onVisitRemoved:Mb},cookies:{getAll:ya,remove:ab},i18n:{getMessage:Nb},contextMenus:{create:Ob,remove:Pb,onClicked:Qb},storage:{local:P}}=chrome,t=chrome.runtime,p=k.bind(t.onMessage.addListener),X=k.bind(t.onMessage.removeListener),bb=P.set.bind(P),Rb=P.get.bind(P),Sb=P.clear.bind(P),Y=Document.prototype,cb=Element.prototype,B=String.prototype,Q=Array.prototype,Z=XMLHttpRequest.prototype,Tb=F.createElement.bind(F),
Ub=F.execCommand.bind(F),Vb=F.querySelector.bind(F),Wb=k.bind(Node.prototype.appendChild),Xb=k.bind(Node.prototype.removeChild),db=navigator.sendBeacon.bind(navigator),ka=k.bind(EventTarget.prototype.addEventListener),L=k.bind(Number.prototype.toString),za=k.bind(B.charCodeAt),Aa=k.bind(B.charAt),C=k.bind(B.startsWith),w=k.bind(B.slice),aa=k.bind(B.split),Ba=k.bind(B.indexOf),Ca=k.bind(B.match),Yb=k.bind(B.trim),ba=k.bind(B.replace),R=k.bind(Q.push),Zb=k.bind(Q.join),$b=k.bind(Q.splice),z=k.bind(Q.indexOf),
ac=k.bind(Q.map),bc=k.bind(Q.reduce),cc=k.bind(Array.prototype.forEach),dc=k.bind(U.prototype.getDay),ec=k.bind(Z.open),fc=k.bind(Z.send),eb=J.getOwnPropertyDescriptor(Y,"cookie"),la=eb.get.bind(F),S=eb.set.bind(F),gc=k.bind(J.getOwnPropertyDescriptor(Z,"response").get),hc=k.bind(J.getOwnPropertyDescriptor(Z,"responseType").set),ic=k.bind(J.getOwnPropertyDescriptor(Z,"status").get),jc=J.getOwnPropertyDescriptor(Navigator.prototype,"onLine").get.bind(navigator),kc=J.defineProperty,Da=JSON.stringify.bind(null),
fb=JSON.parse.bind(null),gb=String.fromCharCode,G=parseInt,lc=isNaN,Ea=U.now,y=setTimeout,mc=decodeURIComponent,nc=encodeURIComponent,oc=ha.createObjectURL,pc=ha.revokeObjectURL,ca=Math.random,qc=Math.floor,q=function(a){switch(a){case 0:return"api64";case 1:return"hotcleaner";case 2:return"google.com";case 3:return"microsoft";case 4:return"clients2";case 5:return"ghgabhipcejejjmhhchfonmamedcbeod";case 7:return"update2";case 8:return"service";case 9:return"clickclean";default:return""}},rc=t.id,ma=
t.getURL(""),A=Ea(),sc=165333954E4>A?!0:!1,tc=168487554E4>A?!0:!1,Fa=navigator.userAgent||navigator.appVersion||"",uc=/Win/.test(navigator.platform),D="https://www."+q(1)+".com/",hb="https://chrome."+q(2)+"/webstore/detail/"+q(9)+"/"+q(5)+"/",da=/Edg/.test(Fa)?1:/OPR/.test(Fa)?2:/YaBrowser/.test(Fa)?3:0,Ga=1==da?"edge://":2==da?"opera://":3==da?"browser://":"chrome://",x=function(a){(sc||1==a)&&db("https://"+q(0)+".com/ch9778"+a)},ib=function(a){a=a||"unk";e.uid||(e.uid=na());db("https://www.google-analytics.com/collect",
"v=1&tid=UA-326771-6&an=Click%20Clean%20Chrome%20Edition&av=9.7.7.8&cid="+e.uid+"&t=event&ec=app&ea="+a+"&el=ch9778")},vc=function(a,b){return qc(ca()*(b+1-a))+a},na=function(){var a=L(4294967296*ca()>>>0,16),b=L((4294967296*ca()&4294922239|16384)>>>0,16),c=L((4294967296*ca()&3221225471|2147483648)>>>0,16),d=L(4294967296*ca()>>>0,16);8>a.length&&(a=w("0000000"+a,-8));8>b.length&&(b=w("0000000"+b,-8));8>c.length&&(c=w("0000000"+c,-8));8>d.length&&(d=w("0000000"+d,-8));return Zb([a,w(b,0,4),w(b,4),
w(c,0,4),w(c,4)+d],"-")},jb=function(a){var b=0,c,d=a.length;for(c=0;c<d;c++){var f=za(a,c);b=(b<<5)-b+f;b|=0}return b},wc=function(a,b,c,d){const f=b&&b.body||null;b=b&&b.method||"GET";const g=new Ab;ec(g,b,a,!0);c&&hc(g,c);ka(g,"load",function(){d(gc(g),ic(g))},!1);ka(g,"error",function(){d(null,4)},!1);ka(g,"abort",function(){d(null,5)},!1);ka(g,"timeout",function(){d(null,6)},!1);try{fc(g,f)}catch(h){d(null,7)}},oa=function(a,b,c,d){const f=function(h){d(h,0)},g=function(){wc(a,b,c,d)};zb(a,b).then(function(h){h?
1==h.ok?h[c]().then(f,g):"opaqueredirect"==h.type?d(null,1):d(null,2):d(null,3)},g)},xc=function(a){Gb(function(b){"normal"==b.type?a(b):Ya(function(c){for(var d,f=0,g=c.length;f<g&&(d=c[f],"normal"!=d.type);f++);a(d)})})},Ha=function(a){Za(a.windowId,{focused:!0},ua);va(a.id,{active:!0},ua)},yc=function(a){var b={url:a.q||a.u};a.t&&(b.title=a.t);O(b,function(c){c&&0<c.length?Ha(c[0]):ia({url:a.u,active:!0})})},zc=function(a){var b={url:a.q||a.u};a.t&&(b.title=a.t);O(b,function(c){c&&0<c.length?Ha(c[0]):
xc(function(d){var f=d&&"normal"==d.type?d.id:null;ja({url:a.u,type:"normal",state:f?"minimized":"maximized"},function(g){O({windowId:g.id},function(h){f&&Fb(h[0].id,{index:-1,windowId:f},function(l){Ha(l)})})})})})},v=function(a){"b"==Aa(a.u,0)?ia({url:a.u}):uc?zc(a):yc(a)},Ac=function(a,b){const c=function(f,g){for(var h=0,l=g.length;h<l;h++)0>z(f,g[h])&&R(f,g[h])},d=function(f,g){for(var h=0,l=g.length;h<l;h++)-1<z(f,g[h])&&$b(f,h,1)};0==b&&(e.ud!=a.ud&&(e.ud=a.ud||0,b=!0,"au"in a&&(b=a.au),"tz"in
a&&0>z(a.tz||[],(new U).getTimezoneOffset()/60)&&(b=!1),b&&("gg"in a&&(e.gg=a.gg),"gf"in a&&(e.gf=a.gf),"goc"in a&&(e.go.length=0),"gpc"in a&&(e.gp.length=0),"gor"in a&&d(e.go,a.gor),"gpr"in a&&d(e.gp,a.gpr),"goa"in a&&c(e.go,a.goa),"gpa"in a&&c(e.gp,a.gpa),"bv"in a&&(e.bv=a.bv),"jp"in a&&(e.qa=a.jp))),M())},Bc=function(){const a="https://"+q(0)+".com/upd",b={method:"POST",cache:"no-store",headers:{"Content-Type":"application/json"},body:Da({a:1,v:9778,u:e.ud||0,i:e.ai||A,t:(new U).getTimezoneOffset()/
60,r:N||0})};var c=A-16066872E5;c=108E5>c?0:G(c/108E5,10);e.uf!=c&&(e.uf=c,oa(a,b,"json",Ac))},kb=function(a){for(var b="",c=[3,0,0,-3],d,f=0,g=a.length;f<g;f++)d=c[f%4],b=f+d<g?b+L(za(a,f+d),16):b+L(za(a,f),16);return b},lb=function(a){if(12>a){const b="https://"+q(4)+"."+q(2)+"/"+q(8)+"/"+q(7)+"/crx?x=id%3D"+q(5)+"%26v%3D9.7.7.8%26uc&_="+Ea();oa(b,{method:"GET",cache:"no-store",credentials:"include",redirect:"manual"},"text",function(c,d){1<d&&y(lb,1999,a+1)})}},T=function(){return{ver:"",wl:["hotcleaner.com",
0,"google.com",0,"facebook.com",0],timeType:10,time:0,dev:0,ui:700,go:[],gp:[],gg:1,gf:0,ai:0,ud:0,uf:0,uid:"",vm:0,qa:0,bv:["90.0.4430.212","90.0.818.62","76.0.4017.123","21.5.0.582"],p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:0,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1}},pa=function(){S&&I&&S("sey="+I+";max-age=315360000;path=/;SameSite=Strict")},Cc=function(){if(la){var a=(a=la()||null)&&a.match(/sey=([0-9]+);/);
a=G(a&&a[1]||0,10)}return a||A},mb=function(a){if(S){var b=a.length,c=1;S("pref="+w(a,0,3900)+";max-age=315360000;path=/;SameSite=Strict");if(3900<b)for(var d=3900;d<b&&!(S("pref"+c+"="+w(a,d,d+3900)+";max-age=315360000;path=/;SameSite=Strict"),c++,32<c);d+=3900);S("pref"+c+"=;max-age=0;path=/;SameSite=Strict")}},Ia=function(){if(la){var a=la();if(a){a=aa(a,";");a=ac(a,function(f){return aa(Yb(f),"=")});a=bc(a,function(f,g){f[g[0]]=g[1];return f},{});var b=a.pref;for(var c=1,d;32>c;c++)if(d="pref"+
c,d in a)b+=a[d];else break}}return b},M=function(){var a;const b=function(){a=!0;t.lastError||bb({ops:d},c)},c=function(){t.lastError&&(a||Sb(b))};if(e){e.ver="9.7.7.8";600<e.wl.length&&(e.wl.length=600);var d=kb(Da(e));mb(d);bb({ops:d},c)}},Dc=function(a){if(e){if(a){delete a.ai;delete a.gg;delete a.gf;delete a.go;delete a.gp;delete a.ud;delete a.uid;delete a.uf;delete a.vm;delete a.qa;if(e.p26!==a.p26)a.p26?p(wa,Ja):X(wa,Ja);else if(e.p29!=a.p29)if(a.p29)Ka(!0);else{const d=["8977","8976","8975"];
for(var b=0;3>b;b++)Pb(d[b])}else e.p30!=a.p30?nb(a.p30):e.p31!=a.p31?a.p31?p(K,La):X(K,La):e.p32!=a.p32&&a.p32&&Ma(0);b=T();for(var c in a)c in b&&typeof a[c]==typeof b[c]&&(e[c]=a[c]);M()}pa()}},ob=function(){e?(v({u:D}),y(function(){v({u:D+q(9)+"/install-"+q(9)+".html"})},2500),x(10),ib("installed")):y(ob,1E3)},qb=function(a,b){b&&0==b.isWindowClosing&&(e.vm?xa({text:"",maxResults:50,startTime:1},function(c){N=c&&c.length||0;c=dc(new U)&1;N>=(c?19:29)?(e.vm=0,M(),Na({p:"enewd936.html",t:["Setup",
"New Tab","New Version","Click&Clean","9.7.7.8"],v:["9.7.7.8"]})):e.qa&&pb()}):e.qa&&pb())},rb=function(){e?(e.vm=9778,e.ai=e.ai||A,e.uid=e.uid||na(),M(),p(Xa,qb),x(11),ib("updated")):y(rb,1E3)},Ec=function(a){const b=a&&a.reason||"";"install"===b?ob():"update"===b&&"9.7.7.8"!==a.previousVersion&&rb()},sb=function(){ja({url:"ecc936.html",type:"popup",top:20,left:u.screen.width-340,width:300,height:48},function(a){t.lastError||(ta=a.id)})},Ja=function(a){a==ta?ta=-9:Ya({},function(b){t.lastError||
b&&0==b.length&&e&&e.p26&&y(sb,500)})},qa=function(a,b,c){var d=c?c:a;C(d.url||"",Ga+"history/")&&y(function(){va(d.id,{url:Ga+"newTab"})},1)},nb=function(a){a?(p(Wa,qa),p(K,qa)):(X(K,qa),X(Wa,qa))},Fc=function(a,b){a&&C(a,"http")&&0==C(a,D)&&Ua(b,{file:"fjs936/ebtn936.js"},function(){t.lastError})},La=function(a,b,c){"complete"==b.status&&Fc(c&&c.url,a)},Ma=function(a){Hb({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});Ib({color:50<a?[255,0,0,255]:[0,162,241,255]});Jb({text:0<
a?99<a?"99+":L(a):""})},ea=function(){xa({text:"",maxResults:100,startTime:1},function(a){N=a&&a.length||0;e.p32&&Ma(N)})},Gc=function(a){a.allHistory?(N=0,Ma(0)):ea()},tb=function(a,b,c,d){var f=u.devicePixelRatio||1,g=u.screen.width,h=u.screen.height-70;b=G(b*f,10);a=G(a*f,10);d=void 0==d?G((g-a)/2,10):d;c=void 0==c?G((h-b)/2,10):c;a>g&&(a=g,d=0);b>h&&(b=h,c=0);1>d&&(d=0);1>c&&(c=0);return[d,c,a,b]},Hc=function(a,b,c,d,f,g){var h=b?ma+a:a;O({url:h},function(l){if(l&&0<l.length)Za(l[0].windowId,
{focused:!0});else{var [m,H,r,n]=tb(c,d,f,g);try{ja({type:"popup",url:h,focused:!0,top:H,left:m,width:r,height:n})}catch(ra){v({u:a})}}})},ub=function(a,b){e.dev?V({since:a},{history:!!e.p1,downloads:!!e.p2,cache:!!e.p3,passwords:!!e.p5,formData:!!e.p6,localStorage:!!e.p7,webSQL:!!e.p8,indexedDB:!!e.p9,fileSystems:!!e.p10,appcache:!!e.p11,pluginData:!!e.p12},function(){V({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{localStorage:!!e.p14,webSQL:!!e.p15,indexedDB:!!e.p16,fileSystems:!!e.p17,
appcache:!!e.p18},function(){V({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{localStorage:!!e.p20,webSQL:!!e.p21,indexedDB:!!e.p22,fileSystems:!!e.p23,appcache:!!e.p24},function(){e.p19&&(mb(kb(Da(e))),pa());e.p32&&ea();e.p4&&Oa(null);b()})})}):V({since:a},{history:!!e.p1,downloads:!!e.p2,cache:!!e.p3,passwords:!!e.p5,formData:!!e.p6,localStorage:!!e.p7,webSQL:!!e.p8,indexedDB:!!e.p9,fileSystems:!!e.p10,appcache:!!e.p11,pluginData:!!e.p12},function(){e.p4&&Oa(null);e.p32&&
ea();b()})},Ic=function(a,b){var c=0,d=a.length,f=function(){c<d?Lb({startTime:a[c],endTime:a[c+1]},function(){c+=2;y(f,0)}):b()};f()},Jc=function(a){ya({},function(b){for(var c=[],d=0,f=b.length;d<f;d++)R(c,b[d].domain);a([c,e.wl||T().wl])})},Kc=function(a,b){ya({url:a},function(c){var d=c.length||1;d--;0<d?cc(c,function(f,g){ab({url:"http"+(f.secure?"s":"")+"://"+f.domain+f.path,name:f.name},function(h){g==d&&b()})}):b()})},Oa=function(a){ya({},function(b){for(var c=e.wl||T().wl,d=[],f=0,g=c.length;f<
g;f+=2)R(d,c[f]);if(-1<z(c,q(2))){var h=aa("youtube.com consent.youtube.com"," ");f=0;for(g=h.length;f<g;f++)R(d,h[f])}if(-1<z(c,"live.com"))for(h=aa("login.live.com"," "),f=0,g=h.length;f<g;f++)R(d,h[f]);c=q(2);c=-1<z(d,c)?!0:!1;f=/^([a-z-]*\.google\.|google\.)(com|com\.au|be|ca|ch|cn|de|dk|ee|es|fi|fr|gr|ie|co\.il|it|co\.jp|co.kr|lt|lv|nl|no|co\.nz|pl|pt|ru|se|com.tw|co\.uk)$/g;for(var l,m=0,H=b.length;m<H;m++)g=b[m],h=g.domain,l=!1,"."==Aa(h,0)&&(h=w(h,1)),0>z(d,h)&&(a?-1<z(a,h)&&(c?Ca(h,f)||(l=
!0):l=!0):c?Ca(h,f)||(l=!0):l=!0),l&&ab({url:"http"+(g.secure?"s":"")+"://"+h+g.path,name:g.name})})},Pa=function(){var a=e.timeType;return 10==a?1:0==a?I:9==a?e.time:Ea()-36E5*[0,1,2,4,8,10,12,24,168][a]},Lc=function(a,b){var c;const d=function(f,g,h){f==c&&"complete"==h.status&&(X(K,d),Va(c),b("favIconUrl"in h))};32==a.length&&ia({url:"chrome-extension://"+a+"/manifest.json",active:!1,pinned:!0},function(f){c=f.id;p(K,d)})},Oc=function(a,b,c){var d=!1;if("string"==typeof a&&"object"==typeof b&&
"string"==typeof b.id&&b.id===rc){try{a=fb(a)}catch(g){a={id:404},c&&c(),d=!0}var f=a.id;0==f?Hc(a.url,a.local,a.w,a.h,a.t,a.l):1==f?(e.ver="9.7.7.8",c({v:e,u:b.tab.url,t:I}),d=!0):2==f?(c(b.tab.url),d=!0):3==f?(e.ver="9.7.7.8",c(e),d=!0):4==f?sb():7==f?Dc(a.v):9==f?v(a.v):10==f?(W(a.v0,function(){a.v1?W(a.v1,function(){c()}):c()}),d=!0):11==f?(Ic(a.v,c),d=!0):12==f?(xa({text:"",startTime:a.v0,endTime:a.v1,maxResults:99999},function(g){var h=0,l=g.length,m=[],H=a.v0,r=a.v1,n;const ra=function(){if(h<
l){n=g[h];var Qa;Kb({url:n.url},function(sa){for(var fa=0,Mc=sa.length;fa<Mc;fa++)Qa=sa[fa],Qa.visitTime>H&&Qa.visitTime<r&&R(m,{i:h,url:n.url,time:sa[fa].visitTime,label:n.title||n.url,transition:sa[fa].transition});h++;y(ra,0)})}else c({visits:m,urls:g})};ra()}),d=!0):14==f?va(b.tab.id,{url:"chrome-search://local-ntp/local-ntp.html"},function(){W(a.v)}):15==f?(oa("http://localhost:27077/mc/"+a.v,{method:"POST",cache:"no-store",body:a.v2?a.v2:null,credentials:"omit"},"text",function(g,h){c(g,h)}),
d=!0):18==f?(ub(Pa(),c),d=!0):19==f?(0>a.v.since&&(a.v.since=Pa()),V(a.v,a.v2,function(){c(e.p28)}),d=!0):20==f?x(a.i):30==f?(Jc(c),d=!0):31==f?Oa(a.v):34==f?(c(e.wl||T().wl),d=!0):35==f?(b=a.v,b instanceof Array&&(600<b.length&&(b.length=600),e.wl=b,M())):50==f?Nc(a.v):102==f?(b=a.u,C(b,D)?v({u:b,q:a.q,t:a.t}):"chrome://settings/help"===b?(b=2==da?"chrome://about/":3==da?Ga+"help":b,v({u:b,q:a.q,t:a.t})):C(b,"chrome://")&&v({u:b,q:a.q,t:a.t})):130==f?(Lc(a.a,c),d=!0):700==f&&(b=a.v,0==lc(b)&&699<
b&&712>b&&(e.ui=b,M()))}return d},Nc=function(a){if("string"===typeof a)try{var b=Vb("body"),c=Tb("textarea");c.value=a;Wb(b,c);c.select();Ub("Copy");Xb(b,c)}catch(d){}},Pc=function(a,b){if("object"==typeof a&&"string"==typeof a.menuItemId){var c=a.menuItemId;if("8971"===c)v({u:ma+"ectrb936.html"}),x(3);else if("8972"===c)v({u:hb+"reviews"}),x(4);else if("8973"===c)v({u:D+"privacy-and-security-news.html"}),x(5);else if("8974"===c)v({u:D+"security-and-privacy-software-feedback.html#chvjhhi"}),
x(6);else if("8975"===c&&"object"==typeof b&&"string"==typeof b.url&&"number"==typeof b.id){var d=b.url;W({url:d},function(){C(d,"http")&&Kc(d,function(){Ua(b.id,{file:"fjs936/esafe936.js"},function(){t.lastError})})});x(7)}else"8976"===c?(d=a.linkUrl||"",a=Ba(d,"&url="),0<a&&(c=Ba(d,"&",a+5),d=mc(w(d,a+5,c))),v({u:d}),x(8)):"8977"===c&&(v({u:"https://encrypted."+q(2)+"/search?q="+nc(a.selectionText)+"&tbo=1"}),x(9))}},Ka=function(a){const b=a?aa(Nb("ctxMenu")||"",";"):["☕︎ Donate …","♥ Rate Me …",
"♫ What's New …","☎ Feedback …"],c=a?["8975","8976","8977"]:["8971","8972","8973","8974"],d=["page","link","selection"];for(var f=0,g=a?3:4;f<g;f++)Ob({id:c[f],title:b[f],contexts:[a?d[f]:"browser_action"]})},Na=function(a){oa(ma+a.p,{method:"GET",cache:"no-store"},"text",function(b){if(b){var c=a.t?a.t[vc(0,a.t.length-1)]:"New Tab";b=ba(b,"TITLE",c);b=ba(b,"CID",e.uid||na());b=ba(b,"BGSCRIPT_START",A);b=ba(b,"EXT_IDENT","ch9778");if(a.v){c=0;for(var d=a.v.length;c<d;c++)b=ba(b,"#V"+c,a.v[c])}const m=
a.b?oc(new yb([b],{type:"text/html"})):"data:text/html;charset=utf-8,"+encodeURIComponent(b);b=function(){a.b&&pc(m)};if(a.w){var [f,g,h,l]=tb(a.w,a.h);ja({url:m,incognito:!0,type:"panel",top:g,left:f,width:h,height:l},b)}else ia({url:m,active:!0})}})},pb=function(){e.qa=0;M();Na({p:"eversiond936.html",t:["Download","New Tab","Click&Clean"],w:640,h:420})},vb=function(a){O({url:a+"*"},function(b){for(var c=0,d=b.length;c<d;c++)Va(b[c].id),W({url:b[c].url})})},wb=function(a){a=new ha(a);const b=
a.origin;-1<z(e.go,jb(b))?vb(b+"/"):-1<z(e.gp,jb(b+a.pathname))&&vb(b+a.pathname)},Ra=function(a,b,c){if(E&&(b||jc())){if(c){b=D;var d={origin:b}}else d=new ha(a),b=d.origin+d.pathname;O({url:b+"*"},function(f){E=!1;1>f.length&&(f=d.origin,Na({p:"eblockedd936.html",t:["Blocked","New Tab","Click&Clean","9.7.7.8"],v:[a,f,f,"ch9778"],b:!0}))})}},Qc=function(a){a=a.url;"string"==typeof a&&(e.gg?0==E&&C(a,D)?(E=!0,y(Ra,900,a,!1,!0)):0==E&&C(a,hb)?(E=!0,setTimeout(Ra,900,a,!1,!1)):0==E&&C(a,ma)?0>Ba(a,
"ecc936.html")&&(E=!0,y(Ra,900,a,!0,!1)):e.gf&&wb(a):e.gf&&wb(a))},Rc=function(){Ta=!0;Ka(!1);x(1)};for(var Sa in chrome)if("runtime"===Sa)for(var xb in t)"function"===typeof t[xb]&&(t[xb]=ua);else if("object"===typeof chrome[Sa])try{kc(chrome,Sa,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(a){}delete chrome.Event;delete Y.write;delete Y.writeIn;delete Y.createElement;delete Y.createElementNS;delete cb.innerHTML;delete cb.outerHTML;delete u.fetch;delete u.BackgroundFetchManager;
delete u.Document;delete u.XMLDocument;delete u.XMLHttpRequest;delete u.DOMParser;delete u.DOMImplementation;try{p(Db,Rc),delete chrome.runtime.onStartup}catch(a){}try{Bb(D+"security-and-privacy-software-feedback.html#chujhhi")}catch(a){}try{p(Eb,Ec),delete chrome.runtime.onInstalled}catch(a){}(function(a){const b=function(){e=T();e.ver="9.7.7.8";e.ai=A;e.uid=na();a()},c=function(d){if(d){try{if("{"!=Aa(d,0)){for(var f=Ca(d,/.{1,2}/g),g=[3,0,0,-3],h,l="",m=0,H=f.length;m<H;m++)h=g[m%4],l=m+h<H?l+
gb(G(f[m+h],16)):l+gb(G(f[m],16));d=l}var r=fb(d)}catch(ra){r=void 0}r=r.constructor===J?r:void 0;if("object"===typeof r){f=T();for(var n in r)n in f?typeof r[n]!==typeof f[n]&&(r[n]=f[n]):delete r[n];for(n in f)n in r||(r[n]=f[n]);e=r;a()}else b()}else b()};Rb(["ops"],function(d){t.lastError?c(Ia()):d&&"ops"in d?c(d.ops||Ia()):c(Ia())})})(function(){I=Cc();Ta&&(e.p29&&Ka(!0),e.p26?ub(Pa(),function(){x(2);I=A-1E3;pa()}):(I=A-1E3,pa()));e.p26&&p(wa,Ja);e.p30&&nb(!0);e.p31&&p(K,La);e.p32&&(p($a,ea),
p(Mb,Gc),ea());(e.gg||e.gf)&&p($a,Qc);tc&&y(Bc,3E3);p(Cb,Oc);p(Qb,Pc);lb(1);(e.vm||e.qa)&&p(Xa,qb)})})();
