// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2021 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20210406
'use strict';(function(){var Z;const A=window;var r=document,aa=function(){};const k=Function.prototype.call,w=Event,na="CustomElementRegistry"in A,{runtime:{sendMessage:oa,connect:Ea},i18n:{getMessage:Fa}}=chrome,ba=Document.prototype,E=Element.prototype,ca=String.prototype,ia=Array.prototype,da=Node.prototype,F=r.createElement.bind(r),Ga=r.createElementNS.bind(r),pa=r.querySelector.bind(r),ja=r.createTextNode.bind(r),ka=r.createDocumentFragment.bind(r),y=k.bind(EventTarget.prototype.addEventListener),
qa=k.bind(w.prototype.stopPropagation);k.bind(w.prototype.preventDefault);const t=k.bind(da.appendChild),la=k.bind(da.insertBefore),T=k.bind(da.removeChild),ra=k.bind(E.hasAttribute),q=k.bind(E.getAttribute),C=k.bind(E.setAttribute),R=k.bind(E.removeAttribute),sa=k.bind(E.querySelectorAll),ma=E.attachShadow?k.bind(E.attachShadow):null,Ha=k.bind(DocumentFragment.prototype.querySelector),ta=k.bind(ca.slice),ua=k.bind(ca.indexOf),va=k.bind(ca.split),wa=k.bind(ca.match),G=k.bind(ia.indexOf),H=k.bind(ia.push),
Ia=k.bind(ia.sort),Ja=JSON.stringify,U=parseInt,xa=setTimeout,ya=Object.defineProperty,Ka=(r=Object.getOwnPropertyDescriptor(da,"textContent"))&&r.get?k.bind(r.get):aa,z=r&&r.set?k.bind(r.set):aa,La=chrome.runtime.getURL(""),N=function(l,B){l=Ja(l);B?oa(l,B):oa(l)},I=function(l){N({id:20,i:l},null)},h=function(l){return ma&&na?Ha(Z,l):pa(l)},Pa=function(){var l=-1;const B=function(){return va("youtube.com consent.youtube.com"," ")},V=function(){return/^([a-z-]*\.google\.|google\.)(com|com\.au|be|ca|ch|cn|de|dk|ee|es|fi|fr|gr|ie|co\.il|it|co\.jp|co.kr|lt|lv|nl|no|co\.nz|pl|pt|ru|se|com.tw|co\.uk)$/g},
L=function(){J(1);for(var a=h("#list0");a.firstElementChild;)T(a,a.firstElementChild);for(a=h("#list1");a.firstElementChild;)T(a,a.firstElementChild);N({id:30},function(b){var c=b[0];b=b[1];var e=[],d=0,f=0,g=0;if(0<c.length){for(var n=0,m;m=c[n];n++)"."==m.charAt(0)&&(c[n]=ta(m,1));Ia(c,function(K,Ma){return K<Ma?-1:1});var u=G(b,c[0]);for(n=0;m=c[n];n++){p!=m&&(0<d&&(0>u?(H(e,d),f+=d):(b[u+1]=d,g+=d),d=0),u=G(b,m),0>u&&H(e,m));d++;var p=m}0<d&&(0>u?(H(e,d),f+=d):(b[u+1]=d,g+=d))}if(-1<G(b,"google.com")){var D=
B(),W=V(),x=2;e=e.filter(function(K){if(2==x){if(0>G(D,K)&&null==wa(K,W))return x=1,!0;x=0;return!1}if(1==x)return x=2,!0;f-=K;x=2;return!1})}-1<G(b,"live.com")&&(x=2,e=e.filter(function(K){if(2==x){if("login.live.com"!=K)return x=1,!0;x=0;return!1}if(1==x)return x=2,!0;f-=K;x=2;return!1}));za(0,e,1,1);za(1,b,0,0);z(h("#cnt0")," ("+f+")");z(h("#cnt1")," ("+g+")");J(0)})},O=function(a){if(a instanceof w&&a.isTrusted){a=X(this,"on");for(var b=this.parentElement.nextElementSibling.children,c=0,e;e=b[c];c++)ea(e.firstElementChild,
"on",a),ea(e,"on",a)}},P=function(a){if(a instanceof w&&a.isTrusted){var b=q(this.parentNode,"data-domain");N({id:9,v:{u:"https://"+b+"/"}},null);qa(a)}},fa=function(a){if(a instanceof w&&a.isTrusted){qa(a);var b=this.parentElement,c=q(b.parentNode,"data-id");a=q(b,"data-domain");var e=U(q(b,"data-count"),10),d;1!=c&&(d=[a]);N({id:31,v:d},null);xa(function(){0==c&&(T(b.parentElement,b),M(c,-e))},1E3)}},v=function(a){if(a instanceof w&&a.isTrusted){J(1);I(78);var b=this.parentElement.nextElementSibling;
a=sa(b,".item[on]");if(0<a.length){for(var c=[],e=q(b,"data-id"),d=0,f=0,g;g=a[f];f++)b=q(g,"data-domain"),H(c,b),d+=U(q(g,"data-count"),10),T(g.parentElement,g);N({id:31,v:c},null);xa(function(){M(e,-d);J(0)},3E3)}else J(0)}},S=function(a){a instanceof w&&a.isTrusted&&(J(1),ha(1,0)&&(Q(),L()))},Y=function(a){a instanceof w&&a.isTrusted&&(J(1),ha(0,1)&&(Q(),L()))},Q=function(){var a=h("#list1").children,b=a.length;if(200<b)alert("Maximum number of 200 whitelisted domains exceeded!");else{for(var c=
[],e,d=0;d<b;d++)e=a[d],"item"==e.className&&H(c,q(e,"data-domain"),0);a=c;c=[];e=0;for(d=a.length;e<d;e+=2)b=a[e],0>G(c,b)&&H(c,b,0);a=c;if(-1<G(a,"google.com")){b=B();c=V();d=[];for(var f=0,g=a.length;f<g;f+=2)e=a[f],0>G(b,e)&&0>G(d,e)&&(wa(e,c)||H(d,e,0));H(d,"google.com",0);c=d}else c=a;N({id:35,v:c},null)}J(0)},ha=function(a,b){var c=sa(h("#list"+a),".item[on]"),e=c.length;if(0<e){for(var d=[],f=0,g;g=c[f];f++)H(d,T(g.parentNode,g));Aa(a,b,d)}return e},M=function(a,b){a=h("#cnt"+a);b=U(ta(Ka(a),
2),10)+b;0>b&&(b=0);z(a," ("+b+")")},X=function(a,b){var c=ra(a,b);c?R(a,b):C(a,b,"");return!c},ea=function(a,b,c){c?C(a,b,""):R(a,b)},Na=function(a){if(a instanceof w&&a.isTrusted){var b=ra(this,"on");if(a.shiftKey){if(0>l&&(l=this.parentNode.firstElementChild),a=!b,b=l,this&&b){var c=this;q(c,"data-domain")>q(b,"data-domain")&&(c=b,b=this);for(;c&&q(c,"data-domain")<=q(b,"data-domain");)ea(c,"on",a),ea(c.firstElementChild,"on",a),c=c.nextElementSibling}}else X(this.firstElementChild,"on"),X(this,
"on");l=this}},Ca=function(a,b,c,e,d){var f=F("div");var g=F("button");var n=F("div");var m=F("label");var u=F("button");var p=F("button");f.className="item"+(d?" subsvc":"");g.className="chk";m.className="label elps";p.className="btn link";u.className="btn del";u.title="Delete Cookies";C(f,"data-domain",a);C(f,"data-count",b);D&&C(f,"data-brand",D);e&&(C(g,"on",""),C(f,"on",""));var D=Ba(a);c?z(m,a+" ("+b+")"):D?(z(m,D),ya(g,"brand",{configurable:!1,enumerable:!1,writable:!1,value:D})):z(m,a);t(g,
n);t(f,g);t(f,m);t(f,u);t(f,p);y(u,"click",fa,!1);y(p,"click",P,!1);y(f,"click",Na,!1);return f},za=function(a,b,c,e){a=h("#list"+a);for(var d,f=ka(),g=0;d=b[g];g+=2)d=Ca(d,b[g+1],c,e,!1),t(f,d);t(a,f)},Aa=function(a,b,c){for(var e=h("#list"+b),d,f,g,n,m=0,u=0,p;p=c[u];u++){n=!0;d=q(p,"data-domain");f=p.brand||Ba(d);for(var D=0,W;W=e.children[D];D++)if(g=q(W,"data-domain"),d==g){n=!1;break}else if(d<g){n=U(q(p,"data-count"),10);m+=n;g=p.firstElementChild.nextElementSibling;0==b?z(g,d+" ("+n+")"):
f?(z(g,f),R(p,"on"),R(p.firstElementChild,"on")):z(g,d);la(e,p,W);n=!1;break}n&&(n=U(q(p,"data-count"),10),m+=n,g=p.firstElementChild.nextElementSibling,0==b?z(g,d+" ("+n+")"):f?(z(g,f),R(p,"on"),R(p.firstElementChild,"on")):z(g,d),t(e,p))}0<m&&(M(a,-m),M(b,m))},Da=function(){return[["Click&Clean Preferences","Click&Clean","hotcleaner.com"],["Google Account & Services","GMail, YouTube, …","google.com"],["Facebook","Facebook","facebook.com"],["Twitter","Twitter","twitter.com"],["Yahoo","Yahoo","yahoo.com"],
["Microsoft","SkyDrive, Live Mail, …","live.com"]]},Ba=function(a){for(var b=Da(),c,e=0,d;d=b[e];e++)if(-1<ua(d[2],a)){c=d[0];break}return c},Oa=function(a){if(a instanceof w&&a.isTrusted){a=this.domains||a.target.domains;"google.com"==a?I(86):"live.com"==a?I(90):"hotcleaner.com"==a?I(85):"facebook.com"==a?I(87):"twitter.com"==a?I(88):"yahoo.com"==a&&I(89);a:{var b=h("#list1").children;for(var c,e=0,d;d=b[e];e++)if(c=q(d,"data-domain"),c==a){b=d;break a}b=0}b||(b=Ca(a,0,0,0,!1),Aa(0,1,[b]),Q(),L())}},
J=function(a){h("#shade").className=a?"dbk":"nvw"};(function(){var a=va(Fa("cookies"),";"),b=h("#sel0");b.title=a[0];b=h("#sel1");b.title=a[0];b=h("#t11");la(b,ja(a[1]),b.firstElementChild);b=h("#t12");la(b,ja(a[2]),b.firstElementChild);b=h("#ref");b.title=a[3];b=h("#del0");b.title=a[4];y(h("#sel0"),"click",O,!1);y(h("#sel1"),"click",O,!1);y(h("#ref"),"click",function(c){c instanceof w&&c.isTrusted&&L()},!1);y(h("#del0"),"click",v,!1);y(h("#toc0"),"click",S,!1);y(h("#toc1"),"click",Y,!1)})();L();
(function(){for(var a=h("#services"),b=Da(),c,e,d=ka(),f=0,g=b.length;f<g;f++)c=b[f],e=F("button"),e.className="btn float-left",e.title=c[1],ya(e,"domains",{configurable:!1,enumerable:!1,writable:!1,value:c[2]}),c=new Image,c.className="mt3",c.src="fimg936/fav/"+(f+1)+".png",t(e,c),y(e,"click",Oa,!0),t(d,e);t(a,d)})()},Qa=function(){const l=[{t:1,l:"div",a:[{n:"id",v:"host"}],c:[{t:1,l:"div",a:[{n:"class",v:"view"},{n:"id",v:"view0"}],c:[{t:1,l:"div",a:[{n:"class",v:"hdr"},{n:"id",v:"hdr0"}],c:[{t:1,
l:"button",a:[{n:"id",v:"sel0"},{n:"class",v:"chk"},{n:"title",v:"t10"}],c:[{t:1,l:"div"}]},{t:1,l:"label",a:[{n:"class",v:"label elps"},{n:"id",v:"t11"}],c:[{t:1,l:"span",a:[{n:"id",v:"cnt0"}]}]},{t:1,l:"button",a:[{n:"class",v:"btn"},{n:"id",v:"del0"},{n:"title",v:"t14"}]},{t:1,l:"button",a:[{n:"class",v:"btn"},{n:"id",v:"ref"},{n:"title",v:"t13"}]}]},{t:3,v:" "},{t:1,l:"div",a:[{n:"class",v:"list"},{n:"id",v:"list0"},{n:"data-id",v:"0"}]}]},{t:1,l:"button",a:[{n:"id",v:"toc1"}]},{t:1,l:"button",
a:[{n:"id",v:"toc0"}]},{t:1,l:"div",a:[{n:"class",v:"view"},{n:"id",v:"view1"}],c:[{t:1,l:"div",a:[{n:"class",v:"hdr"},{n:"id",v:"hdr1"}],c:[{t:1,l:"button",a:[{n:"id",v:"sel1"},{n:"class",v:"chk"},{n:"title",v:"t10"}],c:[{t:1,l:"div"}]},{t:1,l:"label",a:[{n:"class",v:"label elps"},{n:"id",v:"t12"}],c:[{t:1,l:"span",a:[{n:"id",v:"cnt1"},{n:"class",v:"nvw"}]}]},{t:1,l:"div",a:[{n:"id",v:"services"}]}]},{t:1,l:"div",a:[{n:"class",v:"list"},{n:"id",v:"list1"},{n:"data-id",v:"1"}]}]},{t:1,l:"div",a:[{n:"id",
v:"shade"}]}]}],B=function(P,fa){for(var v,S,Y,Q=0,ha=fa.length;Q<ha;Q++)if(v=fa[Q],1==v.t){S=v.n?Ga("http://www.w3.org/2000/svg",v.l):F(v.l);for(var M=0,X=v.a&&v.a.length||0;M<X;M++)Y=v.a[M],C(S,Y.n,Y.v);v.c&&B(S,v.c);t(P,S)}else 3==v.t&&t(P,ja(v.v))},V=pa("body"),L=ka(),O=F("link");Z=ma&&na?ma(V,{mode:"closed"}):V;y(O,"load",function(P){P instanceof w&&P.isTrusted&&(B(L,l),t(Z,L),Pa())},!1);C(O,"rel","stylesheet");C(O,"href",La+"fcss936/ecookies936.css");t(Z,O)};aa=function(l){l instanceof w&&
l.isTrusted&&(I(18),N({id:2},function(B){0===ua(B,"https://www.hotcleaner.com/")&&Qa()}))};if(A.top==A)A.location.replace("https://www.hotcleaner.com/cookie-wiper.html");else{for(const l of Object.getOwnPropertyNames(chrome))if("object"===typeof chrome[l])try{Object.defineProperty(chrome,l,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(B){}Object.defineProperty(chrome.runtime,"connect",{configurable:!1,enumerable:!1,writable:!1,value:Ea});delete chrome.Event;delete ba.write;delete ba.writeIn;
delete ba.createElement;delete ba.createElementNS;delete E.innerHTML;delete E.outerHTML;delete A.fetch;delete A.BackgroundFetchManager;delete A.XMLDocument;delete A.XMLHttpRequest;delete A.DOMParser;delete A.DOMImplementation;y(A,"DOMContentLoaded",aa,!0)}})();
