// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2021 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20210406
'use strict';(function(){var Q;const F=window,E=document,da=navigator;var m=Function.prototype.call;const oa=function(){},O=Event,pa=Audio,qa=Image,Ga=da.platform,ra="CustomElementRegistry"in F,sa=chrome.runtime,{runtime:{sendMessage:ta,connect:Ha},tabs:{query:ea,reload:Ia,remove:ua,update:Ja},windows:{create:Ka},i18n:{getMessage:X}}=chrome,R=Document.prototype,S=Element.prototype;var G=String.prototype;const va=Array.prototype,y=E.createElement.bind(E),wa=E.createDocumentFragment.bind(E),xa=E.querySelector.bind(E);
E.querySelectorAll.bind(E);const P=m.bind(EventTarget.prototype.addEventListener);m.bind(EventTarget.prototype.removeEventListener);const p=m.bind(Node.prototype.appendChild),La=m.bind(Node.prototype.removeChild),fa=m.bind(Node.prototype.insertBefore),ya=m.bind(S.setAttribute),ha=S.attachShadow?m.bind(S.attachShadow):null,Ma=m.bind(DocumentFragment.prototype.querySelector),Na=m.bind(HTMLMediaElement.prototype.play),za=m.bind(G.indexOf),Y=m.bind(G.split),Z=m.bind(G.slice),Aa=m.bind(G.match),Oa=m.bind(G.trim),
Pa=m.bind(G.replace),Qa=m.bind(va.map),Ra=m.bind(va.reduce),Ba=m.bind(Array.prototype.forEach),Sa=JSON.stringify,T=parseInt,J=setTimeout;G=Date.now;const ia=F.close,z=Math.random,aa=Math.floor,Ta=Math.max,L=m.bind(Object.getOwnPropertyDescriptor(Node.prototype,"textContent").set),Ca=(m=Object.getOwnPropertyDescriptor(R,"cookie"))&&m.get?m.get.bind(E):oa,ja=m&&m.set?m.set.bind(E):oa,Da=sa.getURL(""),Ua=165333954E4>G()?!0:!1,ba=163053714E4>G()?!0:!1,M=da.appVersion||da.userAgent||"",q=/Edg/.test(M)?
1:/OPR/.test(M)?2:/YaBrowser/.test(M)?3:0,D=1==q?"edge://":2==q?"opera://":3==q?"browser://":"chrome://",Va=/Win/.test(Ga),k=function(a){switch(a){case 0:return"hotcleaner";case 1:return"https://www.";case 2:return"ghgabhipcejejjmhhchfonmamedcbeod";case 3:return"google.com";case 4:return"update";case 5:return"api64";default:return""}},Wa=function(a){var b=Ca();b&&(b=Y(b,";"),b=Qa(b,function(f){return Y(Oa(f),"=")}),b=Ra(b,function(f,h){f[h[0]]=h[1];return f},{}),b=b[a]);return b},u=function(a,b){a=
Sa(a);b?ta(a,b):ta(a)},e=function(a){u({id:20,i:a},null)},g=function(a){u({id:9,v:a},null)},ca=function(a){if(3==a||4==a){var b="https://";b=1==q?b+"blogs.windows.com/msedgedev/author/msedgeteam/":2==q?b+"blogs.opera.com/desktop/":3==q?b+"https://zen.yandex.ru/yandexbrowser":b+(3==a?"blog.google/products/chrome/":"chromereleases.googleblog.com/")}else 5==a?(b=D,b=2==q?b+"about/credits/":b+"credits/"):6==a&&(b=D,b=2==q?b+"about/":b+"version/");return b},H=function(a){var b={},f=k(1)+k(0)+".com/";if(1==
a)if(ba){a="clear remove delete erase manage obliterate sweep".split(" ");var h="browsing private your my my-private chrome".split(" ");var A=["history","data","records"];b.u=f+a[7*z()|0]+"-"+h[6*z()|0]+"-"+A[3*z()|0]+".html";b.q=f+"*";b.t="Clear Browsing History"}else b.u=f+"clear-browsing-history.html";else 2==a?ba?(a=["cookie","browser-cookie","chrome-cookie"],h=["wiper","delete","remove"],b.u=f+a[3*z()|0]+"-"+h[3*z()|0]+".html",b.q=f+"*",b.t="Cookie Wiper *"):b.u=f+"cookie-wiper.html":3==a?ba?
(a=["clickclean","cleaner","my"],h=["private","incognito","safe"],b.u=f+a[3*z()|0]+"-"+h[3*z()|0]+"-mode.html"):b.u=f+"clickclean-private-mode.html":4==a&&(ba?(a=["browser","chrome","navigator"],h=["update","version","release"],A=["scanner","checker"],b.u=f+a[3*z()|0]+"-"+h[3*z()|0]+"-"+A[2*z()|0]+".html",b.q=f+"*",b.t="Browser Update *"):b.u=f+"browser-update-scanner.html");return b},Xa=function(){ea({active:!0,windowType:"normal"},function(a){var b=H(3).u,f;a&&0<a.length&&(f=a[0].url||"");f&&(b+=
"#"+encodeURIComponent(f));Ka({url:b,incognito:!0,state:"maximized"})})},K=function(a){return ha&&ra?Ma(Q,a):xa(a)},ab=function(){var a,b=!1,f="menu0";const h=function(d){if(d instanceof O&&d.isTrusted){var c=d.target.id;f!=c&&(f&&(K("#"+f).className="nav"),f=c,d.target.className="nav act",A(c,null))}},A=function(d,c){var r;c=c||K("#box");"menu0"==d?r=[3,"red","close.png",0,7,0,"options1.png",18,3,"magenta","clear.png",1,7,0,"options1.png",18,7,0,"tabs1.png",2,7,0,"help.png",27,3,"violet","cache.png",
3,7,0,"trash1.png",4,3,"violet","history.png",5,7,0,"trash1.png",6,7,0,"help.png",27,0,"blue","quickscan.png",8,3,"violet","security.png",14,7,0,"test.png",28,0,"choko","cookie.png",15,7,0,"trash1.png",16,7,0,"help.png",27,0,"seawave",a?"cleanup.png":"memory.png",a?12:13,3,"violet","downloads.png",9,7,0,"trash1.png",10,0,"red","defender.png",21,0,"teal","report.png",17,0,"magenta","options.png",18,7,0,"themes.png",19,0,"green","updates.png",20,7,0,"browser.png",20,0,"carbon","incognito.png",11]:"menu1"==
d?r=[3,"seawave","plugins.png",0,3,"green","extensions.png",1,3,"orange","experiments.png",2,3,"magenta","internals.png",3,0,"violet","dns.png",4,3,"violet","history.png",5,0,"violet","cache.png",6,0,"red","key.png",7,3,"blue","version.png",8,7,0,"arrow1.png",9,0,"red","conflicts.png",10,0,"teal","policies.png",11,0,"blue","releases.png",12,7,0,"calendar1.png",13,0,"blue","credits.png",14,0,"teal","bug.png",15]:"menu2"==d?r=[3,"green","winsec.png",0,3,"blue","info.png",1,3,"red","uninstall.png",2,
3,"violet","defragmenter.png",3,3,"magenta","sound.png",4,3,"marine","network.png",5,7,0,"connect.png",6,7,0,"wireless.png",7,3,"teal","devices.png",8,3,"violet","display.png",9,3,"blue","services.png",10,3,"seawave","directx.png",11]:"menu3"==d&&g({u:Da+"ectrb936.html"});if("menu3"!==d){var B=0;d=X(d).split(";");for(var t=wa(),l,n,w,x,v,U,V,W,ka,la,N=0;N<r.length;N+=4)V=N/4,v=r[N],U=r[N+1],W=r[N+2],V="i"+V,W="fimg936/menu/"+W,la=d[r[N+3]],7>v?(ka=0,l=y("div"),n=y("div"),x=y("div"),w=new qa,U=
"btn "+U,2<v?(U+=" wide",l.className="btnBoxWide"):l.className="btnBox",n.id=V,n.className=U,w.className="icn",x.className="txt0",w.dataset.url=w.src=W,L(x,la),p(n,w),p(n,x),p(l,n),p(t,l)):(l=y("div"),v=y("div"),w=new qa,w.src=W,l.id=V,l.className="adt a"+ka,w.className="icnm",v.className="txt1",L(v,la),p(l,w),fa(n,l,x),fa(n,v,x),ka++),B++;for(;c.firstElementChild;)La(c,c.firstElementChild);p(c,t);c.style.display=""}},I=function(d,c,r){ea(c?{active:!0}:{},function(B){Ba(B,function(t,l){c?Ia(t.id):
l?ua(t.id):Ja(t.id,{url:d?"about:blank":"chrome-search://local-ntp/local-ntp.html"});r&&l==B.length-1&&J(r,500)})})},C=function(d,c,r){var B,t=c?d.previousElementSibling:d.firstElementChild;t.src="fimg936/menu/wipe.gif";const l=function(){if(B.p28&&pa){var n=new pa("fimg936/erased.ogg");Na(n)}J(function(){t.src="fimg936/menu/done.png";J(function(){t.src=t.dataset.url;r&&ea({},function(w){Ba(w,function(x,v){ua(x.id)})})},990);b=!1},300)};b||(b=!0,u({id:3},function(n){B=n;c?"cookies"==c?(u({id:31,v:null},
null),J(l,500)):(n={id:19,v:{since:-1},v2:{}},n.v2[c]=!0,u(n,l)):B.p0||r?I(r,0,function(){u({id:18},l)}):u({id:18},function(){B.p25?I(0,1,l):l()})}))},Ya=function(d){if(d instanceof O&&d.isTrusted)if(d=d.target.id?d.target:d.target.parentElement,"menu0"==f){var c=T(Z(d.id||"",1),10);0==c?(e(29),u({id:4},null)):1==c?(u({id:0,local:1,url:"ecleaner936.html",w:770,h:500},null),e(30),ia()):2==c?(12==aa(23*z())+1?g(H(1)):C(d,null,null),e(31)):3==c?(e(32),u({id:0,local:1,url:"ecleaner936.html",w:770,
h:500},null),ia()):4==c?(e(33),I(0,0,0)):5==c?(g({u:k(1)+k(0)+".com/clickclean-quick-start-guide.html"}),e(105)):6==c?(e(34),g({u:k(1)+k(0)+".com/cache-viewer.html"})):7==c?(e(35),C(d,"cache",null)):8==c?(g(H(1)),e(36)):9==c?(12==aa(19*z())+1?g(H(1)):C(d,"history",null),e(37)):10==c?(g({u:k(1)+k(0)+".com/how-to-save-your-browsing-history-before-deleting.html"}),e(103)):11==c?(g({u:k(1)+k(0)+".com/clickclean-scan-for-malware.html"}),e(38)):12==c?(d=k(1)+k(0)+".com/clickclean-app.html",g({u:d+"#chvjhhi",
q:d}),e(45)):13==c?(g({u:k(1)+k(0)+".com/how-to-spot-and-avoid-phishing-scams.html"}),e(106)):14==c?(g(H(2)),e(41)):15==c?(12==aa(19*z())+1?g(H(2)):C(d,"cookies",null),e(42)):16==c?(g({u:k(1)+k(0)+".com/stay-logged-in-and-keep-settings-for-sites.html"}),e(104)):17==c?a?(e(43),u({id:15,v:"00"+(115).toString(16)},null)):(e(44),g({u:D+"system/"})):18==c?(e(39),g({u:D+"downloads/"})):19==c?(e(40),C(d,"downloads",null)):20==c?(g({u:k(1)+k(0)+".com/privacy-and-security-news.html"}),e(77)):21==c?(d=k(1)+
k(0)+".com/security-and-privacy-software-feedback.html",g({u:d+"#chvjhhi",q:d}),e(47)):22==c?(12==aa(29*z())+1?g({u:k(1)+k(0)+".com/clickclean-appearance.html"}):u({id:0,local:1,url:"ecleaner936.html",w:770,h:500},null),ia(),e(48)):23==c?(g({u:k(1)+k(0)+".com/clickclean-appearance.html"}),e(49)):24==c?(d=k(1)+k(0)+".com/clickclean_chrome_update_checker.html",g({u:d+"#chvjhhi",q:d}),e(50)):25==c?(e(76),g(H(4))):26==c&&(e(46),Xa())}else"menu1"==f?(c=T(Z(d.id||"",1),10),0==c?(e(52),g({u:D+"components/"})):
1==c?(e(53),g({u:D+"extensions/"})):2==c?(e(54),g({u:D+"flags/"})):3==c?(e(55),g({u:D+"net-export/"})):4==c?(e(56),g({u:D+"net-internals/#dns"})):5==c?(g(H(1)),e(57)):6==c?(g({u:k(1)+k(0)+".com/cache-viewer.html"}),e(58)):7==c?(e(59),u({id:0,local:1,url:"epgen936.html",w:350,h:216},null)):8==c?(e(60),g({u:ca(6)})):9==c?(e(61),g({u:ca(3)})):10==c?(e(62),g({u:D+(a?"conflicts/":"crashes/")})):11==c?(e(63),g({u:D+"policy/"})):12==c?(e(64),g({u:ca(4)})):13==c?(e(65),g({u:k(1)+"chromium.org/developers/calendar"})):
14==c?(e(66),g({u:ca(5)})):15==c&&(e(67),g({u:"https://code."+k(3)+"/p/chromium/issues/list"}))):"menu2"==f&&(e(68),c=T(Z(d.id||"",1),10)+100,u({id:15,v:"00"+c.toString(16)},null))},Za=function(d){const c=function(x){var v=y("div");v.className=0==x?"nav act":"nav";v.id="menu"+x;L(v,r[x]);P(v,"click",h,!1);return v},r=X("menu").split(";"),B=wa(),t=y("div"),l=y("div"),n=y("div"),w=d&&d.ui||0;t.id="panel";l.id="menu";l.className="w102";n.id="box";700<w&&707>w&&n.classList.add("UI"+w);p(t,l);p(t,n);p(B,
t);p(l,c(0));p(l,c(1));p(l,c(3));A(f,n);p(Q,B);P(n,"click",Ya,!1);J(function(){t.className="w310"},10);Va?u({id:15,v:"000E"},function(x){x?(a=x,l.className="w77",fa(l,c(2),K("#menu3")),J(function(){K("#i17").firstElementChild.src="fimg936/menu/cleanup.png";var v=X("menu0").split(";");L(K("#i17").firstElementChild.nextElementSibling,v[12]);ma(d)},1)):ma(d)}):ma(d)},$a=function(d){sa.lastError?J(na,1E3,1):d?Za(d):J(na,1E3,1)},na=function(){u({id:3},$a)};e(69);na()},bb=function(a){a instanceof O&&a.isTrusted&&
(K(".dlg").classList.add("hide"),ja("dg=q;path=/;SameSite=Strict"),e(91),g(H(4)))},cb=function(a){a instanceof O&&a.isTrusted&&(K(".dlg").classList.add("hide"),ja("dg=q;path=/;SameSite=Strict"),e(92))},Ea=function(){var a=K(".dlg");if(!a){a=X("msg4").split(";");var b=a[0],f=a[1];0<q&&(b=Pa(b,"Chrome",1==q?"Edge":2==q?"Opera":"Yandex"));a=y("div");a.className="dlg";var h=y("p");h.className="dlgTxt";L(h,b);p(a,h);h=y("button");h.className="dlgOk";L(h,f);p(a,h);P(h,"click",bb,!1);h=y("button");h.className=
"dlgX";L(h,"x");p(a,h);P(h,"click",cb,!1);p(Q,a)}a.classList.remove="hide";e(93)},Fa=function(a,b){var f=0;a=Y(a,".");b=Y(b,".");for(var h=Ta(a.length,b.length),A,I,C=0;C<h;C++)if(A=C<a.length?T(a[C],10):0,I=C<b.length?T(b[C],10):0,isNaN(A)&&(A=0),isNaN(I)&&(I=0),A!=I){f=A>I?1:-1;break}return f},ma=function(a){if(Ua&&ja&&Ca&&"q"!==Wa("dg")&&!Aa(M,/CrOS|Mobile|Linux|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Chromium|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/)){var b=
1==q?"Edg":2==q?"OPR":3==q?"YaBrowser":"Chrome",f=za(M,b+"/");if(0<f&&(f+=b.length+1,b=za(M," ",f),0>b||b>f))var h=Z(M,f,0<b?b:void 0);h&&(f=1==q?"90.0.818.62":2==q?"76.0.4017.123":3==q?"21.5.0.582":"90.0.4430.212",0>Fa(h,f)?Ea():a&&a.bv&&(f=a.bv[q])&&Aa(f,/^\d+(\.\d+){0,3}$/)&&0>Fa(h,f)&&Ea())}};for(const a of Object.getOwnPropertyNames(chrome))if("object"===typeof chrome[a])try{Object.defineProperty(chrome,a,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(b){}Object.defineProperty(chrome.runtime,
"connect",{configurable:!1,enumerable:!1,writable:!1,value:Ha});delete chrome.Event;delete R.write;delete R.writeIn;delete R.createElement;delete R.createElementNS;delete S.innerHTML;delete S.outerHTML;delete F.fetch;delete F.BackgroundFetchManager;delete F.XMLDocument;delete F.XMLHttpRequest;delete F.DOMParser;delete F.DOMImplementation;P(F,"DOMContentLoaded",function(a){if(a instanceof O&&a.isTrusted){a=xa("body");const b=y("link");Q=ha&&ra?ha(a,{mode:"closed"}):a;P(b,"load",function(f){f instanceof
O&&f.isTrusted&&ab()},!1);ya(b,"rel","stylesheet");ya(b,"href",Da+"fcss936/emenu936.css");p(Q,b)}},!0)})();
