// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2021 Vlad & Serge Strukoff. All Rights Reserved.
// Minified by Google Closure Compiler 20210406
'use strict';(function(){var g;const f=window;var c=document,e=Function.prototype.call;const h=Event,A="CustomElementRegistry"in f,{runtime:{sendMessage:B,connect:J}}=chrome,p=Document.prototype,k=Element.prototype,C=c.createElement.bind(c),K=c.createElementNS.bind(c),L=c.createTextNode.bind(c),M=c.createDocumentFragment.bind(c),D=c.querySelector.bind(c),u=e.bind(EventTarget.prototype.addEventListener),v=e.bind(k.setAttribute),w=k.attachShadow?e.bind(k.attachShadow):null,N=e.bind(DocumentFragment.prototype.querySelector),
O=e.bind(h.prototype.preventDefault),P=e.bind(h.prototype.stopPropagation),Q=e.bind(HTMLElement.prototype.focus),q=e.bind(Node.prototype.appendChild);c=e.bind(String.prototype.startsWith);const R=JSON.stringify,E=/Edg/.test(navigator.appVersion||navigator.userAgent||""),F=chrome.runtime.getURL("");/Win/.test(navigator.platform);const l=function(a,b){a=R(a);b?B(a,b):B(a)},m=function(a){l({id:20,i:a},null)},S=function(a){return w&&A?N(g,a):D(a)},T=function(){Q(S(".a0"));u(g,"click",function(a){if(a instanceof
h&&a.isTrusted){var b=a.target;b=b.className||b.parentElement&&b.parentElement.className||"";"a1"===b?(l({id:0,local:1,url:"ecleaner936.html",w:770,h:500},null),m(22)):"a2"===b?(l({id:9,v:{u:E?"https://microsoftedge.microsoft.com/addons/detail/dacknjoogbepndbemlmljdobinliojbk":"https://chrome.google.com/webstore/detail/clickclean/ghgabhipcejejjmhhchfonmamedcbeod/reviews"}},null),m(23)):"a3"===b?(l({id:9,v:{u:"https://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvjhhi",q:"https://www.hotcleaner.com/security-and-privacy-software-feedback.html"}},
null),m(24)):(l({id:9,v:{u:E?"https://www.hotcleaner.com/clickclean-for-microsoft-edge.html":"https://www.hotcleaner.com/clickclean_chrome.html"}},null),m(25));O(a);P(a)}},!0)},W=function(){const a=[{t:1,l:"div",a:[{n:"class",v:"hst"}],c:[{t:1,l:"h1",c:[{t:3,v:"Thank You for using Click&Clean"}]},{t:1,l:"h3",c:[{t:3,v:"Software Made to Make Your Life Better!"}]},{t:1,l:"button",a:[{n:"class",v:"a0"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg936/opt-home64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Home"}]}]},{t:1,
l:"button",a:[{n:"class",v:"a1"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg936/opt-opt64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Options"}]}]},{t:1,l:"button",a:[{n:"class",v:"a2"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg936/opt-rate64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Rate"}]}]},{t:1,l:"button",a:[{n:"class",v:"a3"}],c:[{t:1,l:"img",a:[{n:"src",v:"fimg936/opt-contact64.webp"}]},{t:1,l:"b",c:[{t:3,v:"Support"}]}]},{t:1,l:"br"}]}],b=function(n,G){for(var d,r,x,y=0,U=G.length;y<U;y++)if(d=G[y],1==d.t){r=d.n?K("http://www.w3.org/2000/svg",
d.l):C(d.l);for(var z=0,V=d.a&&d.a.length||0;z<V;z++)x=d.a[z],v(r,x.n,x.v);d.c&&b(r,d.c);q(n,r)}else 3==d.t&&q(n,L(d.v))},H=D("body"),I=M(),t=C("link");g=w&&A?w(H,{mode:"closed"}):H;u(t,"load",function(n){n instanceof h&&n.isTrusted&&(b(I,a),q(g,I),T())},!1);v(t,"rel","stylesheet");v(t,"href",F+"fcss936/eoptions936.css");q(g,t)};e=function(a){a instanceof h&&a.isTrusted&&(m(26),W())};if(c(f.location.href,F)){for(const a of Object.getOwnPropertyNames(chrome))if("object"===typeof chrome[a])try{Object.defineProperty(chrome,
a,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(b){}Object.defineProperty(chrome.runtime,"connect",{configurable:!1,enumerable:!1,writable:!1,value:J});delete chrome.Event;delete p.write;delete p.writeIn;delete p.createElement;delete p.createElementNS;delete k.innerHTML;delete k.outerHTML;delete f.fetch;delete f.BackgroundFetchManager;delete f.XMLDocument;delete f.XMLHttpRequest;delete f.DOMParser;delete f.DOMImplementation;u(f,"DOMContentLoaded",e,!0)}})();
